---
title: "Imprint/Impressum"
---

**Impressum**

Angaben gemäß § 5 TMG \
Inhaltlich verantwortlich für den Inhalt der Website:

Alexander Vossen \
Tilburg University \
Jheronimus Academy of Data Science (JADS)\
St. Janssingel 92 \
5211 DA ‘s-Hertogenbosch \
The Netherlands 

Kontakt \
[a.vossen\@tilburguniversity.edu](mailto:a.vossen@tilburguniversity.edu)


Haftung für Links

Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich. Sollten uns rechtswidrige Inhalte auf verlinkten Seiten bekannt werden, entfernen wir diese Links unverzüglich.

**Imprint**

Statement according to § 5 TMG \
Responsible for the content of this website:

Alexander Vossen \
Tilburg University \
Jheronimus Academy of Data Science (JADS)\
St. Janssingel 92 \
5211 DA ‘s-Hertogenbosch \
The Netherlands 

Contact \
[a.vossen\@tilburguniversity.edu](mailto:a.vossen@tilburguniversity.edu)

Liability for Links

Despite careful content control, we assume no liability for the content of external links. The operators of the linked pages are solely responsible for their content. Should we become aware of any illegal content on linked pages, we will remove these links immediately.